---
steps:
  - label: ':bazel: Build & Test'
    commands:
      - bazel build --config=ci
        //chapter02/... //chapter03/... //chapter04/... //chapter05/... //chapter06/...
        //chapter07/... //chapter08/... //chapter09/... //chapter10/... //chapter11/...
      - bazel test --config=ci
        //chapter02/... //chapter03/... //chapter04/... //chapter05/...
        //chapter07/... //chapter08/... //chapter09/... //chapter11/...
    branches: "!main"

  - label: ':codecov: + :codeclimate: Test & Coverage'
    commands:
      - bazel coverage --config=ci
        //chapter02/... //chapter03/... //chapter04/... //chapter05/...
        //chapter07/... //chapter08/... //chapter09/... //chapter11/...
      - sh .buildkite/upload_coverage.sh "$(bazel info output_path)/_coverage/_coverage_report.dat"
    branches: "main"
