---
steps:
  - label: ':bazel: Build'
    commands:
      - bazel build //chapter02/... //chapter03/... //chapter04/... //chapter05/...
        //chapter06/... //chapter07/... //chapter08/... //chapter09/... //chapter10/...
        //chapter11/...
  - label: ':bazel: Test'
    commands:
      - bazel test //chapter02/... //chapter03/... //chapter04/... //chapter05/...
        //chapter07/... //chapter08/... //chapter09/... //chapter11/...
