---
steps:
  - label: ':bazel: Test & Coverage'
    commands:
      - bazel coverage --combined_report=lcov //chapter02/... //chapter03/... //chapter04/...
        //chapter05/... //chapter07/... //chapter08/... //chapter09/... //chapter11/...
  - wait
  - label: ':codecov: Upload Coverage'
    commands:
      - codecov -f "$(bazel info output_path)/_coverage/_coverage_report.dat"
    branches: "main"
