---
steps:
  - label: ':bazel: Build & Test'
    commands:
      - bazel build //chapter02/... //chapter03/... //chapter04/... //chapter05/...
        //chapter06/... //chapter07/... //chapter08/... //chapter09/... //chapter10/...
        //chapter11/...
      - bazel test //chapter02/... //chapter03/... //chapter04/... //chapter05/...
        //chapter07/... //chapter08/... //chapter09/... //chapter11/...
  - label: ':codecov: Coverage'
    commands:
      - bazel coverage --instrumentation_filter "^//chapter../src/main/java/com/fillmore_labs[/:]"
        //chapter02/... //chapter03/... //chapter04/... //chapter05/...
        //chapter07/... //chapter08/... //chapter09/... //chapter11/...
      - codecov -s "$(bazel info bazel-testlogs)"
    if: build.branch == "main"
